package com.example.greenloop.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val primaryLight = Color(0xFF386B01)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFB8F397)
val onPrimaryContainerLight = Color(0xFF0D2000)
val secondaryLight = Color(0xFF55624C)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFD9E7CB)
val onSecondaryContainerLight = Color(0xFF131F0D)
val tertiaryLight = Color(0xFF386663)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBCEBE7)
val onTertiaryContainerLight = Color(0xFF00201E)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF9FAEF)
val onBackgroundLight = Color(0xFF1A1C16)
val surfaceLight = Color(0xFFF9FAEF)
val onSurfaceLight = Color(0xFF1A1C16)
val surfaceVariantLight = Color(0xFFE1E4D5)
val onSurfaceVariantLight = Color(0xFF44483D)
val outlineLight = Color(0xFF75796C)

// Dark Theme Colors
val primaryDark = Color(0xFF9DD67D)
val onPrimaryDark = Color(0xFF1A3700)
val primaryContainerDark = Color(0xFF285000)
val onPrimaryContainerDark = Color(0xFFB8F397)
val secondaryDark = Color(0xFFBDCBB0)
val onSecondaryDark = Color(0xFF273421)
val secondaryContainerDark = Color(0xFF3E4A36)
val onSecondaryContainerDark = Color(0xFFD9E7CB)
val tertiaryDark = Color(0xFFA0CFCB)
val onTertiaryDark = Color(0xFF003734)
val tertiaryContainerDark = Color(0xFF1E4E4B)
val onTertiaryContainerDark = Color(0xFFBCEBE7)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF12140E)
val onBackgroundDark = Color(0xFFE2E3D8)
val surfaceDark = Color(0xFF12140E)
val onSurfaceDark = Color(0xFFE2E3D8)
val surfaceVariantDark = Color(0xFF44483D)
val onSurfaceVariantDark = Color(0xFFC5C8BA)
val outlineDark = Color(0xFF8F9285)
